apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: resource-ops-dev

resources:
- namespace.yaml
- ../../base

patches:
- path: patch-replicas.yaml
- path: patch-configmap.yaml
- path: patch-external-secret.yaml

images:
- name: team2-backend
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team2-backend
  newTag: sha-fafcb82
