apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: resource-app-secret
spec:
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: /team2-project-cluster/resource-ops/prod/SPRING_DATASOURCE_URL
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: /team2-project-cluster/resource-ops/prod/SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: /team2-project-cluster/resource-ops/prod/SPRING_DATASOURCE_PASSWORD
