apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: resource-app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: resource-app-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: /team2-project-cluster/resource-ops/base/SPRING_DATASOURCE_URL
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: /team2-project-cluster/resource-ops/base/SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: /team2-project-cluster/resource-ops/base/SPRING_DATASOURCE_PASSWORD
