apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - external-secret.yaml
  - gateway.yaml
  - httproute.yaml
  - load-balancer-configuration.yaml
  - target-group-configuration.yaml

labels:
  - pairs:
      app.kubernetes.io/name: resource-app
      app.kubernetes.io/part-of: resource-ops
