apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-app-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::495599735720:role/team2-project-cluster-cloudwatch-reader
automountServiceAccountToken: true
